const ACTIONS = {
	TOGGLE_DARK_MODE: "TOGGLE_DARK_MODE",
	CHANGE_PAGE: "CHANGE_PAGE",
	QUIZ_UPDATE_SETTINGS: "QUIZ_UPDATE_SETTINGS",
	QUIZ_ADD_ANSWERS: "QUIZ_ADD_ANSWERS",
	QUIZ_RESET_ANSWERS: "QUIZ_RESET_ANSWERS",
	QUIZ_INCREMENT_TIMES_PLAYED: "QUIZ_INCREMENT_TIMES_PLAYED",
};

export default ACTIONS;
